"""initial jobs table

Revision ID: 902dd3102737
Revises:
Create Date: 2026-09-07 16:18:29.159032
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "902dd3102737"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("stage", sa.String(length=24), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("scale", sa.Integer(), nullable=False),
        sa.Column("output_format", sa.String(length=8), nullable=False),
        sa.Column("quality", sa.Integer(), nullable=True),
        sa.Column("preserve_metadata", sa.Boolean(), nullable=False),
        sa.Column("enhance_options", sa.JSON(), nullable=False),
        sa.Column("input_path", sa.Text(), nullable=False),
        sa.Column("output_path", sa.Text(), nullable=True),
        sa.Column("thumbnail_path", sa.Text(), nullable=True),
        sa.Column("input_width", sa.Integer(), nullable=False),
        sa.Column("input_height", sa.Integer(), nullable=False),
        sa.Column("input_bytes", sa.Integer(), nullable=False),
        sa.Column("input_format", sa.String(length=8), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("output_width", sa.Integer(), nullable=True),
        sa.Column("output_height", sa.Integer(), nullable=True),
        sa.Column("output_bytes", sa.Integer(), nullable=True),
        sa.Column("device", sa.String(length=8), nullable=True),
        sa.Column("tile_size", sa.Integer(), nullable=True),
        sa.Column("passes", sa.Integer(), nullable=True),
        sa.Column("processing_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=48), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_technical", sa.Text(), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_jobs_expires_at", ["expires_at"], unique=False)
        batch_op.create_index("ix_jobs_status", ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_status")
        batch_op.drop_index("ix_jobs_expires_at")
        batch_op.drop_index("ix_jobs_created_at")

    op.drop_table("jobs")
    # ### end Alembic commands ###
